# Tornado Synthetic Dataset - 3D Steady
> [cgl datasets](https://cgl.ethz.ch/research/visualization/data.php)
> Steady means no time is involved

In [1]:
import numpy as np
import pyvista as pv

In [2]:
file = '..\\Data\\tornado3d.vti'
mesh = pv.read(file)

In [14]:
w,v,u = mesh.point_data['w'], mesh.point_data['v'], mesh.point_data['u']

vectors = np.empty((mesh.n_points, 3))
vectors[:,0] = u
vectors[:,1] = v
vectors[:,2] = w

print(vectors)
mesh['vectors'] = vectors


[[-0.12064955 -1.93279207 -0.01465584]
 [-0.07151286 -1.94863772 -0.01521232]
 [-0.02303854 -1.96307242 -0.01575776]
 ...
 [ 1.77152324  0.57372099  0.        ]
 [ 1.74369514  0.60435438  0.        ]
 [ 1.71609509  0.63592207  0.        ]]


In [15]:
print(mesh['vectors'])

[[-0.12064955 -1.93279207 -0.01465584]
 [-0.07151286 -1.94863772 -0.01521232]
 [-0.02303854 -1.96307242 -0.01575776]
 ...
 [ 1.77152324  0.57372099  0.        ]
 [ 1.74369514  0.60435438  0.        ]
 [ 1.71609509  0.63592207  0.        ]]


In [4]:
# https://docs.pyvista.org/api/core/_autosummary/pyvista.RectilinearGrid.streamlines.html

boundary = mesh.decimate_boundary().extract_all_edges()

# Sphere Source
stream1, seed_pts = mesh.streamlines(
    'vectors', 
    return_source=True,
    n_points=1,
    source_radius=0,
    source_center=(-4e-11,-4e-11,-4e-11)
)

In [16]:
vectors2 = vectors.copy()
m = np.linalg.norm(vectors, axis=1).max() * 0.01
num = np.random.random_sample(vectors.shape) * 2*m - m
vectors2 += num

print(vectors2)

mesh2 = pv.UniformGrid(
    # dims=dims,
    # spacing=tuple([x*s for x in list(mesh.spacing)]),
    dims=mesh.dimensions,
    spacing=mesh.spacing,
    origin=mesh.origin
)

mesh2['vectors2'] = vectors2


[[-0.06723229 -1.96622484 -0.03207966]
 [-0.04520892 -1.93305769 -0.0096692 ]
 [ 0.01322037 -1.95719396  0.04390694]
 ...
 [ 1.74254669  0.54094335  0.04933983]
 [ 1.73776451  0.56120097  0.04262678]
 [ 1.69192077  0.60731638 -0.05661044]]


In [17]:
print(mesh2['vectors2'])

[[-0.06723229 -1.96622484 -0.03207966]
 [-0.04520892 -1.93305769 -0.0096692 ]
 [ 0.01322037 -1.95719396  0.04390694]
 ...
 [ 1.74254669  0.54094335  0.04933983]
 [ 1.73776451  0.56120097  0.04262678]
 [ 1.69192077  0.60731638 -0.05661044]]


In [20]:
# https://docs.pyvista.org/api/core/_autosummary/pyvista.RectilinearGrid.streamlines.html

boundary = mesh2.decimate_boundary().extract_all_edges()

# Sphere Source
stream2 = mesh2.streamlines_from_source(
    vectors='vectors2', 
    source=seed_pts
)

In [21]:
print(stream2)

PolyData (0x1b08e167ee0)
  N Cells:	2
  N Points:	252
  X Bounds:	-3.981e+00, 1.036e+00
  Y Bounds:	-3.116e+00, 2.469e+00
  Z Bounds:	-1.751e+00, 6.171e-01
  N Arrays:	8



In [22]:
a = 0

print(stream1.cell_points(a)[0,:])
print(stream2.cell_points(a)[0,:])

p = pv.Plotter()
p.add_mesh(stream1.cell_points(a), color='red')
p.add_mesh(stream2.cell_points(a), color='blue')
p.add_mesh(boundary, color='grey', opacity=.25)
p.show()

[-3.99999998e-11 -3.99999998e-11 -3.99999998e-11]
[-3.99999998e-11 -3.99999998e-11 -3.99999998e-11]


ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)